import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");
const dataDir = path.join(root, "data", "prompts_by_locale");

const REPO = "awesome-gemini-omni-prompts";
const UTM = `?utm_source=github&utm_campaign=${REPO}`;

const en = {
  repoTitle: "Awesome Gemini Omni Prompts",
  subtitle: "A curated collection of Gemini Omni prompt examples with real previews generated via Atlas Cloud.",
  note:
    "This repository tracks official and prompt-guide examples for Gemini Omni. Each entry includes a preview video plus a localized prompt.",
  overviewTitle: "🤔 What is Gemini Omni?",
  overviewBody:
    "Gemini Omni is Google's multimodal video model — text-to-video, image-to-video and reference-to-video with native, synchronized audio. On Atlas Cloud it runs as `google/gemini-omni-flash/*`. Every preview below was generated through Atlas Cloud from the listed prompt.",
  current: "Current",
  otherLanguages: "Other Languages",
  stats: "Statistics",
  metric: "Metric",
  count: "Count",
  totalPrompts: "Total Prompts",
  categories: "Categories",
  previewVideos: "Preview Videos",
  lastUpdated: "Last Updated",
  browseByCategory: "Browse by Category",
  allPrompts: "All Prompts",
  category: "Category",
  source: "Source",
  author: "Author",
  language: "Language",
  video: "Video",
  view: "View",
  description: "Description",
  prompt: "Prompt",
  autoGenerated: "This README is auto-generated from locale data in `data/prompts_by_locale`.",
};

const zh = {
  repoTitle: "Awesome Gemini Omni 提示词大全",
  subtitle: "收录 Gemini Omni 官方示例与提示词指南示例，内嵌 OSS 视频预览。",
  note:
    "这个仓库整理了 Gemini Omni 的公开视频案例。每条数据都带视频预览，并提供本地化提示词，方便直接复用。",
  overviewTitle: "🤔 什么是 Gemini Omni？",
  overviewBody:
    "Gemini Omni 是 Google 的多模态视频生成模型，支持文生视频、图生视频、参考生视频，并原生音画同步。在 Atlas Cloud 上通过 `google/gemini-omni-flash/*` 调用。下面每条 prompt 的预览都由 Atlas Cloud 实际跑出。",
  current: "当前",
  otherLanguages: "其他语言",
  stats: "统计数据",
  metric: "指标",
  count: "数量",
  totalPrompts: "提示词总数",
  categories: "分类数",
  previewVideos: "预览视频数",
  lastUpdated: "最后更新",
  browseByCategory: "按分类浏览",
  allPrompts: "全部提示词",
  category: "分类",
  source: "来源",
  author: "作者",
  language: "语言",
  video: "视频",
  view: "查看",
  description: "描述",
  prompt: "提示词",
  autoGenerated: "此 README 由 `data/prompts_by_locale` 数据自动生成。",
};

const zhTW = {
  ...zh,
  repoTitle: "Awesome Gemini Omni 提示詞大全",
  subtitle: "收錄 Gemini Omni 官方示例與提示詞指南示例，內嵌 OSS 影片預覽。",
  note: "這個倉庫整理了 Gemini Omni 的公開影片案例。每條資料都帶影片預覽，並提供本地化提示詞，方便直接複用。",
  current: "目前",
  otherLanguages: "其他語言",
  stats: "統計資料",
  metric: "指標",
  count: "數量",
  totalPrompts: "提示詞總數",
  categories: "分類數",
  previewVideos: "預覽影片數",
  lastUpdated: "最後更新",
  browseByCategory: "按分類瀏覽",
  allPrompts: "全部提示詞",
  category: "分類",
  language: "語言",
  video: "影片",
  prompt: "提示詞",
  autoGenerated: "此 README 由 `data/prompts_by_locale` 資料自動生成。",
};

const jaJP = {
  ...en,
  repoTitle: "Awesome Gemini Omni プロンプト集",
  subtitle: "Gemini Omni の公式例とプロンプトガイド例を、OSS 動画プレビュー付きでまとめたコレクションです。",
  note:
    "このリポジトリでは Gemini Omni の公開動画サンプルを整理しています。各エントリにはプレビュー動画とローカライズ済みプロンプトが含まれます。",
  current: "現在",
  otherLanguages: "他の言語",
  view: "表示",
  stats: "統計",
  metric: "項目",
  count: "数",
  totalPrompts: "総プロンプト数",
  categories: "カテゴリ数",
  previewVideos: "プレビュー動画数",
  lastUpdated: "最終更新",
  browseByCategory: "カテゴリ別に見る",
  allPrompts: "すべてのプロンプト",
  category: "カテゴリ",
  source: "ソース",
  author: "作者",
  language: "言語",
  video: "動画",
  description: "説明",
  prompt: "プロンプト",
  autoGenerated: "`data/prompts_by_locale` のデータから自動生成された README です。",
};

const koKR = {
  ...en,
  repoTitle: "Awesome Gemini Omni 프롬프트 모음",
  subtitle: "Gemini Omni 공식 예시와 프롬프트 가이드 예시를 OSS 비디오 미리보기와 함께 정리한 컬렉션입니다.",
  note:
    "이 저장소는 Gemini Omni의 공개 비디오 사례를 정리합니다. 각 항목에는 미리보기 비디오와 현지화된 프롬프트가 포함됩니다.",
  current: "현재",
  otherLanguages: "다른 언어",
  view: "보기",
  stats: "통계",
  metric: "항목",
  count: "수량",
  totalPrompts: "전체 프롬프트",
  categories: "카테고리 수",
  previewVideos: "미리보기 비디오 수",
  lastUpdated: "마지막 업데이트",
  browseByCategory: "카테고리별 보기",
  allPrompts: "전체 프롬프트",
  category: "카테고리",
  source: "출처",
  author: "작성자",
  language: "언어",
  video: "비디오",
  description: "설명",
  prompt: "프롬프트",
  autoGenerated: "이 README는 `data/prompts_by_locale` 데이터에서 자동 생성됩니다.",
};

const thTH = {
  ...en,
  repoTitle: "รวมพรอมต์ Awesome Gemini Omni",
  subtitle: "คอลเลกชันตัวอย่างพรอมต์ Gemini Omni พร้อมวิดีโอตัวอย่างจาก OSS ที่คัดสรรมาแล้ว",
  note:
    "รีโพนี้รวบรวมตัวอย่างวิดีโอสาธารณะของ Gemini Omni แต่ละรายการมีวิดีโอตัวอย่างพร้อมพรอมต์ที่รองรับการแปลภาษา",
  current: "ปัจจุบัน",
  otherLanguages: "ภาษาอื่น",
  view: "ดู",
  stats: "สถิติ",
  metric: "รายการ",
  count: "จำนวน",
  totalPrompts: "พรอมต์ทั้งหมด",
  categories: "จำนวนหมวดหมู่",
  previewVideos: "จำนวนวิดีโอตัวอย่าง",
  lastUpdated: "อัปเดตล่าสุด",
  browseByCategory: "เรียกดูตามหมวดหมู่",
  allPrompts: "พรอมต์ทั้งหมด",
  category: "หมวดหมู่",
  source: "แหล่งที่มา",
  author: "ผู้เขียน",
  language: "ภาษา",
  video: "วิดีโอ",
  description: "คำอธิบาย",
  prompt: "พรอมต์",
  autoGenerated: "README นี้สร้างอัตโนมัติจากข้อมูลใน `data/prompts_by_locale`",
};

const viVN = {
  ...en,
  repoTitle: "Tong Hop Prompt Gemini Omni",
  subtitle: "Bo suu tap cac vi du prompt Gemini Omni kem video xem truoc OSS duoc chon loc.",
  note:
    "Kho nay tong hop cac vi du video cong khai cua Gemini Omni. Moi muc deu co video xem truoc va prompt da duoc ban dia hoa.",
  current: "Hien tai",
  otherLanguages: "Ngon ngu khac",
  view: "Xem",
  stats: "Thong ke",
  metric: "Muc",
  count: "So luong",
  totalPrompts: "Tong so Prompt",
  categories: "So danh muc",
  previewVideos: "So video xem truoc",
  lastUpdated: "Cap nhat lan cuoi",
  browseByCategory: "Duyet theo danh muc",
  allPrompts: "Tat ca Prompt",
  category: "Danh muc",
  source: "Nguon",
  author: "Tac gia",
  language: "Ngon ngu",
  video: "Video",
  description: "Mo ta",
  prompt: "Prompt",
  autoGenerated: "README nay duoc tao tu dong tu du lieu trong `data/prompts_by_locale`.",
};

const hiIN = {
  ...en,
  repoTitle: "Awesome Gemini Omni Prompt Sangrah",
  subtitle: "OSS video preview ke saath Gemini Omni prompt examples ka curated collection.",
  note:
    "Yeh repository Gemini Omni ke public video examples ko organize karti hai. Har entry me preview video aur localized prompt shamil hai.",
  current: "Vartaman",
  otherLanguages: "Anya Bhashaen",
  view: "Dekhen",
  stats: "Aankde",
  metric: "Suchak",
  count: "Ginti",
  totalPrompts: "Kul Prompts",
  categories: "Categories",
  previewVideos: "Preview Videos",
  lastUpdated: "Aakhri Update",
  browseByCategory: "Category ke anusar dekhen",
  allPrompts: "Sabhi Prompts",
  category: "Category",
  source: "Source",
  author: "Author",
  language: "Bhasha",
  video: "Video",
  description: "Varnan",
  prompt: "Prompt",
  autoGenerated: "Yeh README `data/prompts_by_locale` ke data se auto-generated hai.",
};

const es = {
  ...en,
  repoTitle: "Awesome Gemini Omni Prompts",
  subtitle: "Una coleccion curada de ejemplos de prompts para Gemini Omni con vista previa de video OSS integrada.",
  note:
    "Este repositorio organiza ejemplos publicos de video de Gemini Omni. Cada entrada incluye un video de vista previa y un prompt localizado.",
  current: "Actual",
  otherLanguages: "Otros Idiomas",
  view: "Ver",
  stats: "Estadisticas",
  metric: "Metrica",
  count: "Cantidad",
  totalPrompts: "Prompts Totales",
  categories: "Categorias",
  previewVideos: "Videos de Vista Previa",
  lastUpdated: "Ultima Actualizacion",
  browseByCategory: "Explorar por Categoria",
  allPrompts: "Todos los Prompts",
  category: "Categoria",
  source: "Fuente",
  author: "Autor",
  language: "Idioma",
  video: "Video",
  description: "Descripcion",
  prompt: "Prompt",
  autoGenerated: "Este README se genera automaticamente a partir de `data/prompts_by_locale`.",
};

const deDE = {
  ...en,
  repoTitle: "Awesome Gemini Omni Prompts",
  subtitle: "Eine kuratierte Sammlung von Gemini-Omni-Promptbeispielen mit eingebetteten OSS-Videovorschauen.",
  note:
    "Dieses Repository organisiert offentliche Videobeispiele fur Gemini Omni. Jeder Eintrag enthalt eine Vorschau und einen lokalisierten Prompt.",
  current: "Aktuell",
  otherLanguages: "Weitere Sprachen",
  view: "Ansehen",
  stats: "Statistiken",
  metric: "Metrik",
  count: "Anzahl",
  totalPrompts: "Prompts Insgesamt",
  categories: "Kategorien",
  previewVideos: "Vorschauvideos",
  lastUpdated: "Zuletzt aktualisiert",
  browseByCategory: "Nach Kategorie durchsuchen",
  allPrompts: "Alle Prompts",
  category: "Kategorie",
  source: "Quelle",
  author: "Autor",
  language: "Sprache",
  video: "Video",
  description: "Beschreibung",
  prompt: "Prompt",
  autoGenerated: "Diese README wird automatisch aus `data/prompts_by_locale` erzeugt.",
};

const frFR = {
  ...en,
  repoTitle: "Awesome Gemini Omni Prompts",
  subtitle: "Une collection de prompts Gemini Omni avec apercus video OSS integres.",
  note:
    "Ce depot organise des exemples video publics de Gemini Omni. Chaque entree comprend une video d'apercu et un prompt localise.",
  current: "Actuel",
  otherLanguages: "Autres Langues",
  view: "Voir",
  stats: "Statistiques",
  metric: "Mesure",
  count: "Nombre",
  totalPrompts: "Nombre Total de Prompts",
  categories: "Categories",
  previewVideos: "Videos d'Apercu",
  lastUpdated: "Derniere Mise a Jour",
  browseByCategory: "Parcourir par Categorie",
  allPrompts: "Tous les Prompts",
  category: "Categorie",
  source: "Source",
  author: "Auteur",
  language: "Langue",
  video: "Video",
  description: "Description",
  prompt: "Prompt",
  autoGenerated: "Ce README est genere automatiquement depuis `data/prompts_by_locale`.",
};

const itIT = {
  ...en,
  repoTitle: "Awesome Gemini Omni Prompts",
  subtitle: "Una raccolta curata di esempi di prompt Gemini Omni con anteprime video OSS integrate.",
  note:
    "Questo repository organizza esempi video pubblici di Gemini Omni. Ogni voce include un video di anteprima e un prompt localizzato.",
  current: "Corrente",
  otherLanguages: "Altre Lingue",
  view: "Vedi",
  stats: "Statistiche",
  metric: "Metrica",
  count: "Conteggio",
  totalPrompts: "Prompt Totali",
  categories: "Categorie",
  previewVideos: "Video di Anteprima",
  lastUpdated: "Ultimo Aggiornamento",
  browseByCategory: "Sfoglia per Categoria",
  allPrompts: "Tutti i Prompt",
  category: "Categoria",
  source: "Fonte",
  author: "Autore",
  language: "Lingua",
  video: "Video",
  description: "Descrizione",
  prompt: "Prompt",
  autoGenerated: "Questo README e generato automaticamente dai dati in `data/prompts_by_locale`.",
};

const pt = {
  ...en,
  repoTitle: "Awesome Gemini Omni Prompts",
  subtitle: "Uma colecao curada de exemplos de prompts Gemini Omni com previews de video OSS incorporados.",
  note:
    "Este repositorio organiza exemplos publicos de video do Gemini Omni. Cada entrada inclui um video de previa e um prompt localizado.",
  current: "Atual",
  otherLanguages: "Outros Idiomas",
  view: "Ver",
  stats: "Estatisticas",
  metric: "Metrica",
  count: "Quantidade",
  totalPrompts: "Total de Prompts",
  categories: "Categorias",
  previewVideos: "Videos de Previa",
  lastUpdated: "Ultima Atualizacao",
  browseByCategory: "Navegar por Categoria",
  allPrompts: "Todos os Prompts",
  category: "Categoria",
  source: "Fonte",
  author: "Autor",
  language: "Idioma",
  video: "Video",
  description: "Descricao",
  prompt: "Prompt",
  autoGenerated: "Este README e gerado automaticamente a partir de `data/prompts_by_locale`.",
};

const trTR = {
  ...en,
  repoTitle: "Awesome Gemini Omni Promptlari",
  subtitle: "Yerlesik OSS video onizlemeleriyle Gemini Omni prompt orneklerinin secilmis koleksiyonu.",
  note:
    "Bu depo Gemini Omni icin herkese acik video orneklerini duzenler. Her kayitta bir onizleme videosu ve yerlestirilmis prompt bulunur.",
  current: "Guncel",
  otherLanguages: "Diger Diller",
  view: "Goruntule",
  stats: "Istatistikler",
  metric: "Olcut",
  count: "Sayi",
  totalPrompts: "Toplam Prompt",
  categories: "Kategoriler",
  previewVideos: "Onizleme Videolari",
  lastUpdated: "Son Guncelleme",
  browseByCategory: "Kategoriye Gore Gozat",
  allPrompts: "Tum Promptlar",
  category: "Kategori",
  source: "Kaynak",
  author: "Yazar",
  language: "Dil",
  video: "Video",
  description: "Aciklama",
  prompt: "Prompt",
  autoGenerated: "Bu README `data/prompts_by_locale` verilerinden otomatik uretilmistir.",
};

const locales = [
  { code: "en-US", fileName: "README.md", label: "English", dateLocale: "en-US", strings: en },
  { code: "zh-CN", fileName: "i18n/README_zh.md", label: "简体中文", dateLocale: "zh-CN", strings: zh },
  { code: "zh-TW", fileName: "i18n/README_zh-TW.md", label: "繁體中文", dateLocale: "zh-TW", strings: zhTW },
  { code: "ja-JP", fileName: "i18n/README_ja-JP.md", label: "日本語", dateLocale: "ja-JP", strings: jaJP },
  { code: "ko-KR", fileName: "i18n/README_ko-KR.md", label: "한국어", dateLocale: "ko-KR", strings: koKR },
  { code: "th-TH", fileName: "i18n/README_th-TH.md", label: "ไทย", dateLocale: "th-TH", strings: thTH },
  { code: "vi-VN", fileName: "i18n/README_vi-VN.md", label: "Tiếng Việt", dateLocale: "vi-VN", strings: viVN },
  { code: "hi-IN", fileName: "i18n/README_hi-IN.md", label: "हिन्दी", dateLocale: "hi-IN", strings: hiIN },
  { code: "es-ES", fileName: "i18n/README_es-ES.md", label: "Español", dateLocale: "es-ES", strings: es },
  { code: "es-419", fileName: "i18n/README_es-419.md", label: "Español (Latinoamérica)", dateLocale: "es-419", strings: es },
  { code: "de-DE", fileName: "i18n/README_de-DE.md", label: "Deutsch", dateLocale: "de-DE", strings: deDE },
  { code: "fr-FR", fileName: "i18n/README_fr-FR.md", label: "Français", dateLocale: "fr-FR", strings: frFR },
  { code: "it-IT", fileName: "i18n/README_it-IT.md", label: "Italiano", dateLocale: "it-IT", strings: itIT },
  { code: "pt-BR", fileName: "i18n/README_pt-BR.md", label: "Português (Brasil)", dateLocale: "pt-BR", strings: pt },
  { code: "pt-PT", fileName: "i18n/README_pt-PT.md", label: "Português", dateLocale: "pt-PT", strings: pt },
  { code: "tr-TR", fileName: "i18n/README_tr-TR.md", label: "Türkçe", dateLocale: "tr-TR", strings: trTR },
];

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function promptSortValue(prompt) {
  const match = String(prompt.id).match(/(\d+)/);
  return match ? Number(match[1]) : Number.MAX_SAFE_INTEGER;
}

function groupByCategory(prompts) {
  const grouped = new Map();
  for (const prompt of prompts) {
    if (!grouped.has(prompt.category)) {
      grouped.set(prompt.category, []);
    }
    grouped.get(prompt.category).push(prompt);
  }
  return [...grouped.entries()];
}

function renderHeader(locale, prompts) {
  const { strings } = locale;
  const categoryCount = new Set(prompts.map((item) => item.category)).size;
  const updated = new Intl.DateTimeFormat(locale.dateLocale, {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date());

  const otherLanguages = locales
    .filter((item) => item.code !== locale.code)
    .map((item) => `[${item.label}](https://github.com/AtlasCloudAI/awesome-gemini-omni-prompts/blob/main/${item.fileName})`)
    .join(" | ");

  return [
    `# 🎬 ${strings.repoTitle}`,
    "",
    "![Awesome Gemini Omni Logo](./logo.png)",
    "",
    "[![Awesome](https://awesome.re/badge.svg)](https://awesome.re)",
    "[![Stars](https://img.shields.io/github/stars/AtlasCloudAI/Awesome-Gemini-Omni-API-Prompts?style=flat-square)](https://github.com/AtlasCloudAI/Awesome-Gemini-Omni-API-Prompts/stargazers)",
    "[![License: CC BY 4.0](https://img.shields.io/badge/License-CC_BY_4.0-lightgrey.svg)](LICENSE)",
    `[![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg)](https://github.com/AtlasCloudAI/Awesome-Gemini-Omni-API-Prompts/pulls)`,
    `[![Prompts](https://img.shields.io/badge/prompts-${prompts.length}%2B-blue.svg)](https://github.com/AtlasCloudAI/Awesome-Gemini-Omni-API-Prompts)`,
    "",
    locale.strings.subtitle,
    "",
    locale.strings.note,
    "",
    `- **${strings.current}:** ${locale.label}`,
    `- **${strings.otherLanguages}:** ${otherLanguages}`,
    "",
    `## ${strings.overviewTitle}`,
    "",
    strings.overviewBody,
    "",
    `## 📊 ${strings.stats}`,
    "",
    `| ${strings.metric} | ${strings.count} |`,
    "| --- | ---: |",
    `| ${strings.totalPrompts} | ${prompts.length} |`,
    `| ${strings.categories} | ${categoryCount} |`,
    `| ${strings.previewVideos} | ${prompts.filter((item) => item.video_url).length} |`,
    `| ${strings.lastUpdated} | ${updated} |`,
    "",
    "### 🧩 Supported Models",
    "",
    "- 🎬 **Video** — Seedance 2.5 · Seedance 2.0 · Seedance 2.0 Mini · Kling 3 · Sora 2 · Veo 3.1 · HappyHorse 1 · Grok Imagine 1.5 · Wan 2.7",
    "- 🎨 **Image** — Seedream 5.0 Pro · Nano Banana 2/Pro · GPT Image 2 · Flux 2 · Seedream 5",
    "- 🧊 **3D** — Seed3D 2.0 · Hunyuan 3D Pro · Hunyuan 3D Rapid",
    "- 💬 **LLM** — Claude · GPT · DeepSeek · MiniMax · Kimi · GLM · Qwen",
    "- 🔊 **Audio** — Grok TTS",
    `- 📚 **Explore more** — [300+ models »](https://www.atlascloud.ai/models${UTM})`,
    "",
    "## ▶ Run any prompt via Atlas Cloud",
    "",
    `**Skill (recommended):** Install [atlas-cloud-skills](https://github.com/AtlasCloudAI/atlas-cloud-skills) in Claude Code, Codex, or Gemini CLI, then just ask it to generate any prompt from this collection.`,
    "",
    `**CLI:** Prefer the terminal? Use [atlascloud-cli](https://github.com/AtlasCloudAI/cli) to run prompts directly.`,
    "",
    `**[→ Get your free Atlas Cloud API key](https://www.atlascloud.ai/console/api-keys${UTM})**`,
    "",
    `## 🏷️ ${strings.browseByCategory}`,
    "",
  ].join("\n");
}

function renderCategoryLinks(grouped) {
  return grouped
    .map(([category], index) => `- [${category}](#category-${index + 1})`)
    .join("\n");
}

function renderPrompt(strings, prompt, index) {
  const videoLink = prompt.preview_url || prompt.video_url;
  return [
    `### No. ${index}: ${prompt.title}`,
    "",
    `- **${strings.category}:** \`${prompt.category}\``,
    `- **${strings.source}:** \`${prompt.source_platform}\``,
    `- **${strings.author}:** ${prompt.author_name}`,
    `- **${strings.language}:** \`${prompt.language}\``,
    `- **${strings.video}:** [${strings.view}](${videoLink})`,
    "",
    `<video src="${escapeHtml(prompt.video_url)}" controls muted playsinline width="720"></video>`,
    "",
    `#### ${strings.description}`,
    "",
    prompt.description,
    "",
    `#### ${strings.prompt}`,
    "",
    "```text",
    prompt.prompt,
    "```",
  ].join("\n");
}

function renderBody(locale, prompts) {
  const grouped = groupByCategory(prompts);
  const sections = [];
  let itemIndex = 1;

  sections.push(renderCategoryLinks(grouped));
  sections.push("");
  sections.push(`## ${locale.strings.allPrompts}`);
  sections.push("");

  for (const [category, items] of grouped) {
    sections.push(`<a id="category-${sections.filter((line) => line.startsWith("<a id=")).length + 1}"></a>`);
    sections.push("");
    sections.push(`### ${category} (${items.length})`);
    sections.push("");

    for (const item of items) {
      sections.push(renderPrompt(locale.strings, item, itemIndex));
      sections.push("");
      itemIndex += 1;
    }
  }

  sections.push(locale.strings.autoGenerated);
  sections.push("");
  sections.push("## More Atlas Cloud Tools");
  sections.push("");
  sections.push("- 💻 [atlascloud-cli](https://github.com/AtlasCloudAI/cli) — run any model from your terminal.");
  sections.push("- 🔌 [MCP Server](https://github.com/AtlasCloudAI/mcp-server) — connect Atlas Cloud to any MCP client.");
  sections.push("- 🧠 [atlas-cloud-skills](https://github.com/AtlasCloudAI/atlas-cloud-skills) — Agent Skills for Claude Code / Codex / Gemini CLI.");
  sections.push("- 🖼️ [atlascloud_comfyui](https://github.com/AtlasCloudAI/atlascloud_comfyui) — ComfyUI custom nodes for Atlas Cloud.");
  sections.push("- 🔁 [n8n-nodes-atlascloud](https://github.com/AtlasCloudAI/n8n-nodes-atlascloud) — n8n automation nodes.");
  sections.push("- 💬 [Discord](https://discord.gg/MWmMr4q9es) — join the community.");
  sections.push(`- 🌐 [Website](https://www.atlascloud.ai/${UTM}) — 300+ models, one API key.`);
  return sections.join("\n");
}

async function loadLocalePrompts(code) {
  const filePath = path.join(dataDir, `${code}.json`);
  try {
    const raw = await fs.readFile(filePath, "utf8");
    return JSON.parse(raw).sort((a, b) => promptSortValue(a) - promptSortValue(b));
  } catch (error) {
    if (error && error.code === "ENOENT") {
      const fallbackCode = code.startsWith("zh-") ? "zh-CN" : "en-US";
      const fallbackPath = path.join(dataDir, `${fallbackCode}.json`);
      const raw = await fs.readFile(fallbackPath, "utf8");
      const prompts = JSON.parse(raw).sort((a, b) => promptSortValue(a) - promptSortValue(b));
      return prompts.map((item) => ({ ...item, language: code }));
    }
    throw error;
  }
}

async function main() {
  for (const locale of locales) {
    const prompts = await loadLocalePrompts(locale.code);
    const output = `${renderHeader(locale, prompts)}\n${renderBody(locale, prompts)}\n`;
    const outPath = path.join(root, locale.fileName);
    await fs.mkdir(path.dirname(outPath), { recursive: true });
    await fs.writeFile(outPath, output, "utf8");
    console.log(`Generated ${locale.fileName}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
