import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");
const dataDir = path.join(root, "data", "prompts_by_locale");

const locales = [
  {
    code: "en-US",
    fileName: "README.md",
    label: "English",
    dateLocale: "en-US",
    otherLanguages: [{ label: "简体中文", fileName: "README_zh.md" }],
    strings: {
      repoTitle: "Awesome Gemini Omni Prompts",
      subtitle:
        "A curated collection of Gemini Omni prompt examples with inline OSS video previews.",
      note:
        "This repository tracks official and prompt-guide examples for Gemini Omni. Each entry includes a preview video plus a localized prompt.",
      current: "Current",
      otherLanguages: "Other Languages",
      stats: "Statistics",
      metric: "Metric",
      count: "Count",
      totalPrompts: "Total Prompts",
      categories: "Categories",
      previewVideos: "Preview Videos",
      lastUpdated: "Last Updated",
      browseByCategory: "Browse By Category",
      allPrompts: "All Prompts",
      category: "Category",
      source: "Source",
      author: "Author",
      language: "Language",
      video: "Video",
      view: "View",
      description: "Description",
      prompt: "Prompt",
      autoGenerated:
        "This README is auto-generated from locale data in `data/prompts_by_locale`.",
    },
  },
  {
    code: "zh-CN",
    fileName: "README_zh.md",
    label: "简体中文",
    dateLocale: "zh-CN",
    otherLanguages: [{ label: "English", fileName: "README.md" }],
    strings: {
      repoTitle: "Awesome Gemini Omni 提示词大全",
      subtitle: "收录 Gemini Omni 官方示例与提示词指南示例，内嵌 OSS 视频预览。",
      note:
        "这个仓库整理了 Gemini Omni 的公开视频案例。每条数据都带视频预览，并提供本地化提示词，方便直接复用。",
      current: "当前",
      otherLanguages: "其他语言",
      stats: "统计数据",
      metric: "指标",
      count: "数量",
      totalPrompts: "提示词总数",
      categories: "分类数",
      previewVideos: "预览视频数",
      lastUpdated: "最后更新",
      browseByCategory: "按分类浏览",
      allPrompts: "全部提示词",
      category: "分类",
      source: "来源",
      author: "作者",
      language: "语言",
      video: "视频",
      view: "查看",
      description: "描述",
      prompt: "提示词",
      autoGenerated: "此 README 由 `data/prompts_by_locale` 数据自动生成。",
    },
  },
];

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function promptSortValue(prompt) {
  const match = String(prompt.id).match(/(\d+)/);
  return match ? Number(match[1]) : Number.MAX_SAFE_INTEGER;
}

function groupByCategory(prompts) {
  const grouped = new Map();
  for (const prompt of prompts) {
    if (!grouped.has(prompt.category)) {
      grouped.set(prompt.category, []);
    }
    grouped.get(prompt.category).push(prompt);
  }
  return [...grouped.entries()];
}

function renderHeader(locale, prompts) {
  const { strings } = locale;
  const categoryCount = new Set(prompts.map((item) => item.category)).size;
  const updated = new Intl.DateTimeFormat(locale.dateLocale, {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date());

  const otherLanguages = locale.otherLanguages
    .map((item) => `[${item.label}](./${item.fileName})`)
    .join(" | ");

  return [
    `# ${strings.repoTitle}`,
    "",
    "![Awesome Gemini Omni Logo](./logo.png)",
    "",
    "[![Awesome](https://awesome.re/badge.svg)](https://awesome.re)",
    "[![Stars](https://img.shields.io/github/stars/AtlasCloudAI/Awesome-Gemini-Omni-API-Prompts?style=flat-square)](https://github.com/AtlasCloudAI/Awesome-Gemini-Omni-API-Prompts/stargazers)",
    "[![License: CC BY 4.0](https://img.shields.io/badge/License-CC_BY_4.0-lightgrey.svg)](LICENSE)",
    "",
    locale.strings.subtitle,
    "",
    locale.strings.note,
    "",
    `- **${strings.current}:** ${locale.label}`,
    `- **${strings.otherLanguages}:** ${otherLanguages}`,
    "",
    `## ${strings.stats}`,
    "",
    `| ${strings.metric} | ${strings.count} |`,
    "| --- | ---: |",
    `| ${strings.totalPrompts} | ${prompts.length} |`,
    `| ${strings.categories} | ${categoryCount} |`,
    `| ${strings.previewVideos} | ${prompts.filter((item) => item.video_url).length} |`,
    `| ${strings.lastUpdated} | ${updated} |`,
    "",
    `## ${strings.browseByCategory}`,
    "",
  ].join("\n");
}

function renderCategoryLinks(grouped) {
  return grouped
    .map(([category], index) => `- [${category}](#category-${index + 1})`)
    .join("\n");
}

function renderPrompt(strings, prompt, index) {
  return [
    `### No. ${index}: ${prompt.title}`,
    "",
    `- **${strings.category}:** \`${prompt.category}\``,
    `- **${strings.source}:** \`${prompt.source_platform}\``,
    `- **${strings.author}:** ${prompt.author_name}`,
    `- **${strings.language}:** \`${prompt.language}\``,
    `- **${strings.video}:** [${strings.view}](${prompt.video_url})`,
    "",
    `<video src="${escapeHtml(prompt.video_url)}" controls muted playsinline width="720"></video>`,
    "",
    `#### ${strings.description}`,
    "",
    prompt.description,
    "",
    `#### ${strings.prompt}`,
    "",
    "```text",
    prompt.prompt,
    "```",
  ].join("\n");
}

function renderBody(locale, prompts) {
  const grouped = groupByCategory(prompts);
  const sections = [];
  let itemIndex = 1;

  sections.push(renderCategoryLinks(grouped));
  sections.push("");
  sections.push(`## ${locale.strings.allPrompts}`);
  sections.push("");

  for (const [category, items] of grouped) {
    sections.push(`<a id="category-${sections.filter((line) => line.startsWith("<a id=")).length + 1}"></a>`);
    sections.push("");
    sections.push(`### ${category} (${items.length})`);
    sections.push("");

    for (const item of items) {
      sections.push(renderPrompt(locale.strings, item, itemIndex));
      sections.push("");
      itemIndex += 1;
    }
  }

  sections.push(locale.strings.autoGenerated);
  return sections.join("\n");
}

async function loadLocalePrompts(code) {
  const filePath = path.join(dataDir, `${code}.json`);
  const raw = await fs.readFile(filePath, "utf8");
  return JSON.parse(raw).sort((a, b) => promptSortValue(a) - promptSortValue(b));
}

async function main() {
  for (const locale of locales) {
    const prompts = await loadLocalePrompts(locale.code);
    const output = `${renderHeader(locale, prompts)}\n${renderBody(locale, prompts)}\n`;
    await fs.writeFile(path.join(root, locale.fileName), output, "utf8");
    console.log(`Generated ${locale.fileName}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
