import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..");
const dataDir = path.join(root, "data", "prompts_by_locale");

const englishStrings = {
  repoTitle: "Awesome Gemini Omni Prompts",
  subtitle: "A curated collection of Gemini Omni prompt examples with inline OSS video previews.",
  note:
    "This repository tracks official and prompt-guide examples for Gemini Omni. Each entry includes a preview video plus a localized prompt.",
  current: "Current",
  otherLanguages: "Other Languages",
  stats: "Statistics",
  metric: "Metric",
  count: "Count",
  totalPrompts: "Total Prompts",
  categories: "Categories",
  previewVideos: "Preview Videos",
  lastUpdated: "Last Updated",
  browseByCategory: "Browse By Category",
  allPrompts: "All Prompts",
  category: "Category",
  source: "Source",
  author: "Author",
  language: "Language",
  video: "Video",
  view: "View",
  description: "Description",
  prompt: "Prompt",
  autoGenerated: "This README is auto-generated from locale data in `data/prompts_by_locale`.",
};

const chineseStrings = {
  repoTitle: "Awesome Gemini Omni 提示词大全",
  subtitle: "收录 Gemini Omni 官方示例与提示词指南示例，内嵌 OSS 视频预览。",
  note:
    "这个仓库整理了 Gemini Omni 的公开视频案例。每条数据都带视频预览，并提供本地化提示词，方便直接复用。",
  current: "当前",
  otherLanguages: "其他语言",
  stats: "统计数据",
  metric: "指标",
  count: "数量",
  totalPrompts: "提示词总数",
  categories: "分类数",
  previewVideos: "预览视频数",
  lastUpdated: "最后更新",
  browseByCategory: "按分类浏览",
  allPrompts: "全部提示词",
  category: "分类",
  source: "来源",
  author: "作者",
  language: "语言",
  video: "视频",
  view: "查看",
  description: "描述",
  prompt: "提示词",
  autoGenerated: "此 README 由 `data/prompts_by_locale` 数据自动生成。",
};

const traditionalChineseStrings = {
  ...chineseStrings,
  repoTitle: "Awesome Gemini Omni 提示詞大全",
  subtitle: "收錄 Gemini Omni 官方示例與提示詞指南示例，內嵌 OSS 影片預覽。",
  note: "這個倉庫整理了 Gemini Omni 的公開影片案例。每條資料都帶影片預覽，並提供本地化提示詞，方便直接複用。",
  current: "目前",
  otherLanguages: "其他語言",
  stats: "統計資料",
  metric: "指標",
  count: "數量",
  totalPrompts: "提示詞總數",
  categories: "分類數",
  previewVideos: "預覽影片數",
  lastUpdated: "最後更新",
  browseByCategory: "按分類瀏覽",
  allPrompts: "全部提示詞",
  category: "分類",
  source: "來源",
  author: "作者",
  language: "語言",
  video: "影片",
  view: "查看",
  description: "描述",
  prompt: "提示詞",
  autoGenerated: "此 README 由 `data/prompts_by_locale` 資料自動生成。",
};

const locales = [
  { code: "en-US", fileName: "README.md", label: "English", dateLocale: "en-US", strings: englishStrings },
  { code: "zh-CN", fileName: "README_zh.md", label: "简体中文", dateLocale: "zh-CN", strings: chineseStrings },
  { code: "zh-TW", fileName: "README_zh-TW.md", label: "繁體中文", dateLocale: "zh-TW", strings: traditionalChineseStrings },
  { code: "ja-JP", fileName: "README_ja-JP.md", label: "日本語", dateLocale: "ja-JP", strings: englishStrings },
  { code: "ko-KR", fileName: "README_ko-KR.md", label: "한국어", dateLocale: "ko-KR", strings: englishStrings },
  { code: "th-TH", fileName: "README_th-TH.md", label: "ไทย", dateLocale: "th-TH", strings: englishStrings },
  { code: "vi-VN", fileName: "README_vi-VN.md", label: "Tiếng Việt", dateLocale: "vi-VN", strings: englishStrings },
  { code: "hi-IN", fileName: "README_hi-IN.md", label: "हिन्दी", dateLocale: "hi-IN", strings: englishStrings },
  { code: "es-ES", fileName: "README_es-ES.md", label: "Español", dateLocale: "es-ES", strings: englishStrings },
  { code: "es-419", fileName: "README_es-419.md", label: "Español (Latinoamérica)", dateLocale: "es-419", strings: englishStrings },
  { code: "de-DE", fileName: "README_de-DE.md", label: "Deutsch", dateLocale: "de-DE", strings: englishStrings },
  { code: "fr-FR", fileName: "README_fr-FR.md", label: "Français", dateLocale: "fr-FR", strings: englishStrings },
  { code: "it-IT", fileName: "README_it-IT.md", label: "Italiano", dateLocale: "it-IT", strings: englishStrings },
  { code: "pt-BR", fileName: "README_pt-BR.md", label: "Português (Brasil)", dateLocale: "pt-BR", strings: englishStrings },
  { code: "pt-PT", fileName: "README_pt-PT.md", label: "Português", dateLocale: "pt-PT", strings: englishStrings },
  { code: "tr-TR", fileName: "README_tr-TR.md", label: "Türkçe", dateLocale: "tr-TR", strings: englishStrings },
];

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function promptSortValue(prompt) {
  const match = String(prompt.id).match(/(\d+)/);
  return match ? Number(match[1]) : Number.MAX_SAFE_INTEGER;
}

function groupByCategory(prompts) {
  const grouped = new Map();
  for (const prompt of prompts) {
    if (!grouped.has(prompt.category)) {
      grouped.set(prompt.category, []);
    }
    grouped.get(prompt.category).push(prompt);
  }
  return [...grouped.entries()];
}

function renderHeader(locale, prompts) {
  const { strings } = locale;
  const categoryCount = new Set(prompts.map((item) => item.category)).size;
  const updated = new Intl.DateTimeFormat(locale.dateLocale, {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).format(new Date());

  const otherLanguages = locales
    .filter((item) => item.code !== locale.code)
    .map((item) => `[${item.label}](./${item.fileName})`)
    .join(" | ");

  return [
    `# ${strings.repoTitle}`,
    "",
    "![Awesome Gemini Omni Logo](./logo.png)",
    "",
    "[![Awesome](https://awesome.re/badge.svg)](https://awesome.re)",
    "[![Stars](https://img.shields.io/github/stars/AtlasCloudAI/Awesome-Gemini-Omni-API-Prompts?style=flat-square)](https://github.com/AtlasCloudAI/Awesome-Gemini-Omni-API-Prompts/stargazers)",
    "[![License: CC BY 4.0](https://img.shields.io/badge/License-CC_BY_4.0-lightgrey.svg)](LICENSE)",
    "",
    locale.strings.subtitle,
    "",
    locale.strings.note,
    "",
    `- **${strings.current}:** ${locale.label}`,
    `- **${strings.otherLanguages}:** ${otherLanguages}`,
    "",
    `## ${strings.stats}`,
    "",
    `| ${strings.metric} | ${strings.count} |`,
    "| --- | ---: |",
    `| ${strings.totalPrompts} | ${prompts.length} |`,
    `| ${strings.categories} | ${categoryCount} |`,
    `| ${strings.previewVideos} | ${prompts.filter((item) => item.video_url).length} |`,
    `| ${strings.lastUpdated} | ${updated} |`,
    "",
    `## ${strings.browseByCategory}`,
    "",
  ].join("\n");
}

function renderCategoryLinks(grouped) {
  return grouped
    .map(([category], index) => `- [${category}](#category-${index + 1})`)
    .join("\n");
}

function renderPrompt(strings, prompt, index) {
  return [
    `### No. ${index}: ${prompt.title}`,
    "",
    `- **${strings.category}:** \`${prompt.category}\``,
    `- **${strings.source}:** \`${prompt.source_platform}\``,
    `- **${strings.author}:** ${prompt.author_name}`,
    `- **${strings.language}:** \`${prompt.language}\``,
    `- **${strings.video}:** [${strings.view}](${prompt.video_url})`,
    "",
    `<video src="${escapeHtml(prompt.video_url)}" controls muted playsinline width="720"></video>`,
    "",
    `#### ${strings.description}`,
    "",
    prompt.description,
    "",
    `#### ${strings.prompt}`,
    "",
    "```text",
    prompt.prompt,
    "```",
  ].join("\n");
}

function renderBody(locale, prompts) {
  const grouped = groupByCategory(prompts);
  const sections = [];
  let itemIndex = 1;

  sections.push(renderCategoryLinks(grouped));
  sections.push("");
  sections.push(`## ${locale.strings.allPrompts}`);
  sections.push("");

  for (const [category, items] of grouped) {
    sections.push(`<a id="category-${sections.filter((line) => line.startsWith("<a id=")).length + 1}"></a>`);
    sections.push("");
    sections.push(`### ${category} (${items.length})`);
    sections.push("");

    for (const item of items) {
      sections.push(renderPrompt(locale.strings, item, itemIndex));
      sections.push("");
      itemIndex += 1;
    }
  }

  sections.push(locale.strings.autoGenerated);
  return sections.join("\n");
}

async function loadLocalePrompts(code) {
  const filePath = path.join(dataDir, `${code}.json`);
  try {
    const raw = await fs.readFile(filePath, "utf8");
    return JSON.parse(raw).sort((a, b) => promptSortValue(a) - promptSortValue(b));
  } catch (error) {
    if (error && error.code === "ENOENT") {
      const fallbackCode = code.startsWith("zh-") ? "zh-CN" : "en-US";
      const fallbackPath = path.join(dataDir, `${fallbackCode}.json`);
      const raw = await fs.readFile(fallbackPath, "utf8");
      const prompts = JSON.parse(raw).sort((a, b) => promptSortValue(a) - promptSortValue(b));
      return prompts.map((item) => ({ ...item, language: code }));
    }
    throw error;
  }
}

async function main() {
  for (const locale of locales) {
    const prompts = await loadLocalePrompts(locale.code);
    const output = `${renderHeader(locale, prompts)}\n${renderBody(locale, prompts)}\n`;
    await fs.writeFile(path.join(root, locale.fileName), output, "utf8");
    console.log(`Generated ${locale.fileName}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
